export const IconBurgerButton = () => {
  return (
    <svg
      width="42"
      height="26"
      viewBox="0 0 42 26"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <line
        x1="3"
        y1="3"
        x2="39"
        y2="3"
        stroke="#FCA311"
        strokeWidth="6"
        strokeLinecap="round"
      />
      <line
        x1="3"
        y1="13"
        x2="39"
        y2="13"
        stroke="#FCA311"
        strokeWidth="6"
        strokeLinecap="round"
      />
      <line
        x1="3"
        y1="23"
        x2="39"
        y2="23"
        stroke="#FCA311"
        strokeWidth="6"
        strokeLinecap="round"
      />
    </svg>
  );
};
