name: Auto Deploy

on:
  push:
    branches:
      - master # Adjust this to match your repository's main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies # If applicable
        run: npm install # Or any other dependency installation command

      - name: Deploy to DigitalOcean
        run: |
          ./deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Pass your SSH private key as an environment variable
