name: Deploy

on:
  push:
    branches:
      - master # Change this to the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=ubuntu-s-1vcpu-2gb-sfo3-01@${{ secrets.HOST }} << 'EOF'
            cd /root/ArtOaa
            git pull
